# Configuration for Twist Mux safety watchdog
twist_mux:
  ros__parameters:
    use_sim_time: true
    topics:
      navigation:
        topic:   'cmd_vel'
        timeout: 0.25   # must be > command period (0.1s at 10 Hz) + DDS jitter
        priority: 10